server:
  port: 8080
spring:
  application:
    name: limits-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
