server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///home/dmitry/dev/learn/java/courses/udemy/spring microservices/spring cloud/git-localconfig-repo
